In [23]:
import pandas as pd

In [24]:
world_population = pd.read_html("https://en.wikipedia.org/wiki/World_population")

In [25]:
type(world_population)

list

In [26]:
world_population[1]

,Region,2022 (percent),2030 (percent),2050 (percent)
0,Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
1,Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
2,Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
3,Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
4,Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
5,Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
6,Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
7,Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
8,World,7942,8512,9687

In [27]:
world_population[2]

,Region,Density (inhabitants/km2),Population (millions),Most populous country,Most populous city (metropolitan area)
0,Asia,104.1,4641,"1,439,090,595 – India","13,515,000 – Tokyo Metropolis (37,400,000 – Gr..."
1,Africa,44.4,1340,"0,211,401,000 – Nigeria","09,500,000 – Cairo (20,076,000 – Greater Cairo)"
2,Europe,73.4,747,"0,146,171,000 – Russia, approx. 110 million in...","13,200,000 – Moscow (20,004,000 – Moscow metro..."
3,Latin America,24.1,653,"0,214,103,000 – Brazil","12,252,000 – São Paulo City (21,650,000 – São ..."
4,Northern America[note 1],14.9,368,"0,332,909,000 – United States","08,804,000 – New York City (23,582,649 – New Y..."
5,Oceania,5,42,"0,025,917,000 – Australia","05,367,000 – Sydney"
6,Antarctica,~0,0.004[86],N/A[note 2],"00,001,258 – McMurdo Station"

In [28]:
tb_01 = world_population[1]

In [29]:
tb_01

,Region,2022 (percent),2030 (percent),2050 (percent)
0,Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
1,Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
2,Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
3,Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
4,Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
5,Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
6,Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
7,Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
8,World,7942,8512,9687

In [30]:
mostPopCountries = world_population[4]

In [31]:
mostPopCountries

,#,Most populous countries,2000,2015,2030[A],"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org."
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_2,Unnamed: 2_level_2,Unnamed: 3_level_2,Unnamed: 4_level_2,Unnamed: 5_level_2
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_3,Unnamed: 2_level_3,Unnamed: 3_level_3,Unnamed: 4_level_3,Unnamed: 5_level_3
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_4,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4,Unnamed: 5_level_4
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_5,Unnamed: 2_level_5,Unnamed: 3_level_5,Unnamed: 4_level_5,Unnamed: 5_level_5
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_6,Unnamed: 2_level_6,Unnamed: 3_level_6,Unnamed: 4_level_6,Unnamed: 5_level_6
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_7,Unnamed: 2_level_7,Unnamed: 3_level_7,Unnamed: 4_level_7,Unnamed: 5_level_7
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_8,Unnamed: 2_level_8,Unnamed: 3_level_8,Unnamed: 4_level_8,Unnamed: 5_level_8
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_9,Unnamed: 2_level_9,Unnamed: 3_level_9,Unnamed: 4_level_9,Unnamed: 5_level_9
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_10,Unnamed: 2_level_10,Unnamed: 3_level_10,Unnamed: 4_level_10,Unnamed: 5_level_10
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_11,Unnamed: 2_level_11,Unnamed: 3_level_11,Unnamed: 4_level_11,Unnamed: 5_level_11
0,NaN,Graphs are unavailable due to technical issues...,NaN,NaN,NaN,NaN
1,1,China[B],1270,1376,1416,NaN
2,2,India,1053,1311,1528,NaN
3,3,United States,283,322,356,NaN
4,4,Indonesia,212,258,295,NaN
5,5,Pakistan,136,208,245,NaN
6,6,Brazil,176,206,228,NaN
7,7,Nigeria,123,182,263,NaN
8,8,Bangladesh,131,161,186,NaN
9,9,Russia,146,146,149,NaN
10,10,Mexico,103,127,148,NaN
11,NaN,World total,6127,7349,8501,NaN
12,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...

In [32]:
mostPopCountries.columns

MultiIndex([(                                                                                                                                                                                           '#', ...),
            (                                                                                                                                                                     'Most populous countries', ...),
            (                                                                                                                                                                                        '2000', ...),
            (                                                                                                                                                                                        '2015', ...),
            (                                                                                                                                                                                     '2030[A]', ...),
            ('Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.', ...)],
           )

In [33]:
mostPopCountries

,#,Most populous countries,2000,2015,2030[A],"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org."
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_2,Unnamed: 2_level_2,Unnamed: 3_level_2,Unnamed: 4_level_2,Unnamed: 5_level_2
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_3,Unnamed: 2_level_3,Unnamed: 3_level_3,Unnamed: 4_level_3,Unnamed: 5_level_3
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_4,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4,Unnamed: 5_level_4
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_5,Unnamed: 2_level_5,Unnamed: 3_level_5,Unnamed: 4_level_5,Unnamed: 5_level_5
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_6,Unnamed: 2_level_6,Unnamed: 3_level_6,Unnamed: 4_level_6,Unnamed: 5_level_6
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_7,Unnamed: 2_level_7,Unnamed: 3_level_7,Unnamed: 4_level_7,Unnamed: 5_level_7
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_8,Unnamed: 2_level_8,Unnamed: 3_level_8,Unnamed: 4_level_8,Unnamed: 5_level_8
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_9,Unnamed: 2_level_9,Unnamed: 3_level_9,Unnamed: 4_level_9,Unnamed: 5_level_9
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_10,Unnamed: 2_level_10,Unnamed: 3_level_10,Unnamed: 4_level_10,Unnamed: 5_level_10
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_11,Unnamed: 2_level_11,Unnamed: 3_level_11,Unnamed: 4_level_11,Unnamed: 5_level_11
0,NaN,Graphs are unavailable due to technical issues...,NaN,NaN,NaN,NaN
1,1,China[B],1270,1376,1416,NaN
2,2,India,1053,1311,1528,NaN
3,3,United States,283,322,356,NaN
4,4,Indonesia,212,258,295,NaN
5,5,Pakistan,136,208,245,NaN
6,6,Brazil,176,206,228,NaN
7,7,Nigeria,123,182,263,NaN
8,8,Bangladesh,131,161,186,NaN
9,9,Russia,146,146,149,NaN
10,10,Mexico,103,127,148,NaN
11,NaN,World total,6127,7349,8501,NaN
12,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...

In [34]:
mostPopCountries = mostPopCountries.drop('#', axis=1)

/var/folders/8k/lzmqyfg539l81tkdwbf3gltc0000gn/T/ipykernel_67925/4003046194.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  mostPopCountries = mostPopCountries.drop('#', axis=1)

In [35]:
mostPopCountries

,Most populous countries,2000,2015,2030[A],"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org."
,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1
,Unnamed: 1_level_2,Unnamed: 2_level_2,Unnamed: 3_level_2,Unnamed: 4_level_2,Unnamed: 5_level_2
,Unnamed: 1_level_3,Unnamed: 2_level_3,Unnamed: 3_level_3,Unnamed: 4_level_3,Unnamed: 5_level_3
,Unnamed: 1_level_4,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4,Unnamed: 5_level_4
,Unnamed: 1_level_5,Unnamed: 2_level_5,Unnamed: 3_level_5,Unnamed: 4_level_5,Unnamed: 5_level_5
,Unnamed: 1_level_6,Unnamed: 2_level_6,Unnamed: 3_level_6,Unnamed: 4_level_6,Unnamed: 5_level_6
,Unnamed: 1_level_7,Unnamed: 2_level_7,Unnamed: 3_level_7,Unnamed: 4_level_7,Unnamed: 5_level_7
,Unnamed: 1_level_8,Unnamed: 2_level_8,Unnamed: 3_level_8,Unnamed: 4_level_8,Unnamed: 5_level_8
,Unnamed: 1_level_9,Unnamed: 2_level_9,Unnamed: 3_level_9,Unnamed: 4_level_9,Unnamed: 5_level_9
,Unnamed: 1_level_10,Unnamed: 2_level_10,Unnamed: 3_level_10,Unnamed: 4_level_10,Unnamed: 5_level_10
,Unnamed: 1_level_11,Unnamed: 2_level_11,Unnamed: 3_level_11,Unnamed: 4_level_11,Unnamed: 5_level_11
0,Graphs are unavailable due to technical issues...,NaN,NaN,NaN,NaN
1,China[B],1270,1376,1416,NaN
2,India,1053,1311,1528,NaN
3,United States,283,322,356,NaN
4,Indonesia,212,258,295,NaN
5,Pakistan,136,208,245,NaN
6,Brazil,176,206,228,NaN
7,Nigeria,123,182,263,NaN
8,Bangladesh,131,161,186,NaN
9,Russia,146,146,149,NaN
10,Mexico,103,127,148,NaN
11,World total,6127,7349,8501,NaN
12,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...

In [36]:
mostPopCountries.columns = ['Most populous countries', '2000', '2015', '2030', 'n']

In [37]:
mostPopCountries

,Most populous countries,2000,2015,2030,n
0,Graphs are unavailable due to technical issues...,NaN,NaN,NaN,NaN
1,China[B],1270,1376,1416,NaN
2,India,1053,1311,1528,NaN
3,United States,283,322,356,NaN
4,Indonesia,212,258,295,NaN
5,Pakistan,136,208,245,NaN
6,Brazil,176,206,228,NaN
7,Nigeria,123,182,263,NaN
8,Bangladesh,131,161,186,NaN
9,Russia,146,146,149,NaN
10,Mexico,103,127,148,NaN
11,World total,6127,7349,8501,NaN
12,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...

In [38]:
mostPopCountries = mostPopCountries.drop('n', axis=1)

In [39]:
mostPopCountries = mostPopCountries.drop(0, axis=0)

In [40]:
mostPopCountries.loc[1, 'Most populous countries'] = 'CHINA'

In [45]:
mostPopCountries = mostPopCountries.reset_index()

In [47]:
mostPopCountries = mostPopCountries.drop('index', axis=1)

In [49]:
mostPopCountries = mostPopCountries.drop(11, axis=0)

In [51]:
mostPopCountries.set_index('Most populous countries')

                         2000  2015  2030
Most populous countries
CHINA                    1270  1376  1416
India                    1053  1311  1528
United States             283   322   356
Indonesia                 212   258   295
Pakistan                  136   208   245
Brazil                    176   206   228
Nigeria                   123   182   263
Bangladesh                131   161   186
Russia                    146   146   149
Mexico                    103   127   148
World total              6127  7349  8501